### ISSUE TITLE
Improve Logging Implementation in data_handler.py

### ISSUE THREAD

**Issue by chasegalloway** [miewliie/california_fire#1]
I just want to preface this by saying that I love this project idea. It's a great cause and seems to have been written well. One thing I would change, however, is the fact that the fire.py module currently uses print statements for debug information, such as the message "Done write data into json file". It would be advantageous to use a more comprehensive logging framework, like Python's built-in logging module.

**Comment by miewliie** [comment]
@chasegalloway Thank you so much for the kind words. I completely agreed with you. 
Would you be interested in doing this? 😊

**Comment by SoniaRaskolnikov** [comment]
If OP isn't interested, I'd be happy to have a look.

**Comment by miewliie** [comment]
@SoniaRaskolnikov Sure  👍

**Comment by miewliie** [comment]
(https://github.com/miewliie/california_fire/commit/9e97ba64fe26abc298ae8c364f2ce60aa0d31fb9)
